stages:
  - build

variables:
  BUILD_HELPERS_VERSION: bd414c2ba2bce5090426774605f3fe4499b902b6

.setup-lbbuild:
  before_script:
    - . .gitlab/gitlab-utils.sh
    - drbd_prepare_tools
    - drbd_fetch_lbbuildctl

# rules clause determining whether to build
.rules-build:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'

build:
  stage: build
  extends: [ .rules-build, .setup-lbbuild ]
  image: $LINBIT_DOCKER_REGISTRY/drbd-utils-build:latest
  cache:
    paths:
      - download
  script:
    - DRBD_UTILS_VERSION=9.0.0.$CI_COMMIT_SHA
    - |
      curl -sSfL -u gitlab-ci-token:$CI_JOB_TOKEN https://gitlab.at.linbit.com/linbit/build-helpers/-/archive/$BUILD_HELPERS_VERSION/ignored.tar.gz | tar -xvzf -
      mv build-helpers-* build-helpers
    - |
      mkdir -p source/drbd-test-bundle
      curl -sSL $LINBIT_REGISTRY_URL/repository/test-suite/drbd-test-bundle.tgz | tar -C source/drbd-test-bundle -xvzf -
    - |
      ./build-helpers/dummy-release.sh drbd-utils "$DRBD_UTILS_VERSION" drbd.spec.in
      ./autogen.sh
      ./configure --prefix=/usr --localstatedir=/var --sysconfdir=/etc --without-83support --without-manual
      make doc .filelist tgz FORCE=1 PRESERVE_DEBIAN=1 REL_VERSION="$DRBD_UTILS_VERSION"
      curl -isSf -u $LINBIT_REGISTRY_USER:$LINBIT_REGISTRY_PASSWORD --upload-file drbd-utils-*.tar.gz $LINBIT_REGISTRY_URL/repository/lbbuild-upstream/
    - |
      META_JSON=$(rq -t < source/drbd-test-bundle/virter/vms.toml | jq '.vms[].metadata')
      echo "$META_JSON" | jq -r '"-d " + .BuildDistribution' \
        | sed -re 's/rhel([[:digit:]])\.[[:digit:]]/rhel\1.0/g' \
        | sort | uniq \
        | parallel --colsep ' ' -k -j24 \
        lbbuildctl build drbd-utils --arch amd64 --ci -v "$DRBD_UTILS_VERSION" -l \
          -e LINBIT_REGISTRY_USER=$LINBIT_REGISTRY_USER \
          -e LINBIT_REGISTRY_PASSWORD=$LINBIT_REGISTRY_PASSWORD \
          -e LINBIT_REGISTRY_URL=$LINBIT_REGISTRY_URL \
          {}
