stages:
  - build
  - test

variables:
  BUILD_HELPERS_VERSION: 330d8122fb0049cae469d3061292a1880127f0bb
  # we have to change the way GitLab CI clones the repository.
  # by default, it is shallow, which gives us a wrong commit count when
  # we do `git rev-list --count origin/master` below.
  GIT_DEPTH: 0
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: normal

.setup-lbbuild:
  before_script:
    - . .gitlab/gitlab-utils.sh
    - drbd_prepare_tools
    - drbd_fetch_lbbuildctl
    - |
      drbd_utils_build () {
        local version="$1"
        local release="$2"
        mkdir -p drbd-test-bundle
        curl -sSL $LINBIT_REGISTRY_URL/repository/test-suite/drbd-test-bundle.tgz | tar -C drbd-test-bundle -xvzf -

        dummy-release.sh drbd-utils "$version" "$release" drbd.spec.in
        sed -i "s/^AC_INIT.*/AC_INIT(DRBD, $version, [drbd-dev@lists.linbit.com])/" configure.ac
        git config --global user.email "invalid@linbit"
        git config --global user.name "Dummy"
        git commit -am "CI $version - $release"
        ./autogen.sh
        ./configure --prefix=/usr --localstatedir=/var --sysconfdir=/etc --without-83support --without-manual
        install /dev/null $(which lbvers.py)
        make debrelease VERSION="$version" FORCE=1
        curl -isSf -u $LINBIT_REGISTRY_USER:$LINBIT_REGISTRY_PASSWORD --upload-file drbd-utils-*.tar.gz $LINBIT_REGISTRY_URL/repository/lbbuild-upstream/

        META_JSON=$(rq -t < drbd-test-bundle/virter/vms.toml | jq '.vms[].metadata')
        echo "$META_JSON" | jq -r '"-d " + .BuildDistribution' \
          | sed -re 's/rhel([[:digit:]])\.[[:digit:]]/rhel\1.0/g' \
          | sort | uniq \
          | parallel --colsep ' ' -k -j24 \
          lbbuildctl build drbd-utils --arch amd64 --ci -v "$DRBD_UTILS_VERSION" -l \
            -e LINBIT_REGISTRY_USER=$LINBIT_REGISTRY_USER \
            -e LINBIT_REGISTRY_PASSWORD=$LINBIT_REGISTRY_PASSWORD \
            -e LINBIT_REGISTRY_URL=$LINBIT_REGISTRY_URL \
            {}
      }

# rules clause determining whether to build
.rules-build:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'

build:
  stage: build
  extends: [ .rules-build, .setup-lbbuild ]
  image: $LINBIT_DOCKER_REGISTRY/build-helpers:$BUILD_HELPERS_VERSION
  cache:
    paths:
      - download
  script:
    - DRBD_UTILS_VERSION=9.0.0.$CI_COMMIT_SHA
    - drbd_utils_build $DRBD_UTILS_VERSION 1
  artifacts:
    paths:
      - drbd-test-bundle
    expire_in: 1 week


build-latest:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  extends: .setup-lbbuild
  image: $LINBIT_DOCKER_REGISTRY/build-helpers:$BUILD_HELPERS_VERSION
  cache:
    paths:
      - download
  script:
    - DRBD_UTILS_VERSION=9.0.0.latest
    - DRBD_UTILS_RELEASE=$(git rev-list --count origin/master)
    - drbd_utils_build $DRBD_UTILS_VERSION $DRBD_UTILS_RELEASE


drbd-tests:
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_ID
  tags:
    - libvirt
  cache:
    paths:
      - download
  script:
    - . drbd-test-bundle/virter/version.env
    - curl -sSfL -u gitlab-ci-token:$CI_JOB_TOKEN $CI_SERVER_URL/linbit/build-helpers/-/archive/$BUILD_HELPERS_VERSION/ignored.tar.gz | tar -xvzf -
    - mv build-helpers-* build-helpers
    - . build-helpers/gitlab-utils.sh
    - |
      ci_prepare_tools
      ci_fetch_rq
      ci_fetch_binary virter virter-$VIRTER_VERSION https://github.com/LINBIT/virter/releases/download/$VIRTER_VERSION/virter-linux-amd64
      ci_fetch_binary vmshed vmshed-$VMSHED_VERSION https://github.com/LINBIT/vmshed/releases/download/$VMSHED_VERSION/vmshed-linux-amd64
    - docker image pull $LINBIT_DOCKER_REGISTRY/drbd9-tests:latest
    - |
      export DRBD_VERSION=9.0.0.latest
      export DRBD_UTILS_VERSION=9.0.0.$CI_COMMIT_SHA-1
      export DRBD9_TESTS_VERSION=latest
      ./drbd-test-bundle/virter/run-test.sh
  dependencies:
    - build
  artifacts:
    # provide a convenient name so that the downloaded artifacts can be identified
    name: $CI_PROJECT_NAME-$CI_JOB_ID
    paths:
      - tests-out/
    when: always
    reports:
      junit: tests-out/test-results/*.xml

